# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171111_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
    ]
