# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171111_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='m', max_length=5024),
        ),
    ]
