# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(max_length=5024),
        ),
    ]
