# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170911_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='club',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', max_length=1024),
        ),
    ]
