# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171114_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=1024),
        ),
    ]
