# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartinsert',
            old_name='item',
            new_name='product',
        ),
    ]
