# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171119_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
