# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20171114_1808'),
        ('cart', '0004_auto_20171119_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinsert',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartinsert',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Item'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, through='cart.CartItem', to='store.Item'),
        ),
        migrations.DeleteModel(
            name='CartInsert',
        ),
    ]
