# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='cart/products'),
        ),
    ]
